@echo off
echo Downloading "scrcpy-win64-v1.22.zip"...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/Genymobile/scrcpy/releases/download/v1.22/scrcpy-win64-v1.22.zip', 'scrcpy-win64-v1.22.zip')"
echo Extracting "scrcpy-win64-v1.22.zip"...
powershell Expand-Archive scrcpy-win64-v1.22.zip -DestinationPath "scrcpy"
echo Downloading "sndcpy-v1.1.zip"...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/rom1v/sndcpy/releases/download/v1.1/sndcpy-v1.1.zip', 'sndcpy-v1.1.zip')"
echo Extracting "sndcpy-v1.1.zip"...
powershell Expand-Archive sndcpy-v1.1.zip -DestinationPath "sndcpy"
echo Downloading "autoadb.exe"...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://tmp.rom1v.com/autoadb/0.1.0/autoadb.exe', 'auto/autoadb.exe')"
echo Excluding residual files...
del scrcpy-win64-v1.22.zip
del sndcpy-v1.1.zip
echo Job done.
echo You can delete this script now.
pause